url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Freelance Web Designer Dubai" # the name of your site, e.g. ACME Corp.
description: Hey There! My name is Lukasz and I am a freelance web designer for Dubai. I'll create your website, develop your wordpress page and help you gain visibility. Search Engine Optimization.

sidebar_text_1: Dubai's Freelance for website design is here. I'm Lukasz and I will help you creating your onlice presence.
